export interface RoadmapStep {
  num: number
  title: string
  difficulty: string
  duration: string
  prerequisites: string[]
  topics: string[]
  why: string
  build: string
  ugProjects: number[]
  commonMistakes: string[]
  tips: string[]
}

export const ROADMAP_STEPS: RoadmapStep[] = [
  {
    num: 1,
    title: 'HTML e CSS fundamentais',
    difficulty: 'Baixa',
    duration: '2-3 semanas',
    prerequisites: ['Saber usar o computador'],
    topics: ['Semântica', 'Box model', 'Flexbox', 'Grid', 'Responsividade'],
    why: 'Toda interface nasce aqui. Sem fluência, tudo o resto trava.',
    build: 'Uma landing page pessoal estática',
    ugProjects: [1],
    commonMistakes: ['Decorar tags sem entender semântica', 'Usar div para tudo'],
    tips: ['Use o DevTools o tempo todo', 'Repita layouts que você admira'],
  },
  {
    num: 2,
    title: 'JavaScript essencial',
    difficulty: 'Média',
    duration: '4-6 semanas',
    prerequisites: ['HTML/CSS básicos'],
    topics: ['Tipos', 'Funções', 'Arrays', 'Objetos', 'DOM', 'Eventos', 'Fetch'],
    why: 'Linguagem da web. Tudo o resto é construído em cima disso.',
    build: 'Um CRUD em JS puro manipulando DOM',
    ugProjects: [1, 2],
    commonMistakes: ['Pular para frameworks antes da fluência em JS'],
    tips: ['Pratique array methods diariamente', 'Escreva fetch sem framework'],
  },
  {
    num: 3,
    title: 'Git e GitHub',
    difficulty: 'Baixa',
    duration: '1-2 semanas',
    prerequisites: ['Conforto no terminal'],
    topics: ['commit', 'branch', 'merge', 'PR', 'rebase', 'remote', 'issues'],
    why: 'Colaboração e portfólio nascem aqui.',
    build: 'Suba todos os projetos anteriores com README',
    ugProjects: [1, 2, 3],
    commonMistakes: ['commits gigantes', 'Mensagens "wip"', 'Não usar branches'],
    tips: ['Commits pequenos e frequentes', 'Use conventional commits'],
  },
  {
    num: 4,
    title: 'React + Componentização',
    difficulty: 'Média',
    duration: '4-6 semanas',
    prerequisites: ['JS intermediário'],
    topics: ['JSX', 'Props', 'useState', 'useEffect', 'Componentes'],
    why: 'React é o padrão de mercado e abre portas.',
    build: 'Aplicativo de tarefas com componentes',
    ugProjects: [3, 4],
    commonMistakes: ['Tudo em um componente só', 'Abusar de useEffect'],
    tips: ['Pense em componentes antes de codar', 'Separe lógica em hooks'],
  },
  {
    num: 5,
    title: 'Next.js e App Router',
    difficulty: 'Média',
    duration: '3-4 semanas',
    prerequisites: ['React sólido'],
    topics: ['App Router', 'Server Components', 'Rotas', 'API routes'],
    why: 'Next é o framework de React mais usado em produção.',
    build: 'Blog pessoal com SSG',
    ugProjects: [5, 6],
    commonMistakes: ['Misturar server e client components sem saber'],
    tips: ['Leia a doc do App Router', 'Use Server Components por padrão'],
  },
  {
    num: 6,
    title: 'TypeScript',
    difficulty: 'Média',
    duration: '3 semanas',
    prerequisites: ['JS intermediário'],
    topics: ['Tipos', 'Interfaces', 'Generics', 'Utility types'],
    why: 'TS reduz bugs e é exigência no mercado moderno.',
    build: 'Reescreva o CRUD em TS',
    ugProjects: [5, 6, 7],
    commonMistakes: ['Usar any em tudo', 'Tipar tudo noite demais'],
    tips: ['Comece pelos tipos das funções', 'Use inference a seu favor'],
  },
  {
    num: 7,
    title: 'Node e APIs',
    difficulty: 'Média',
    duration: '3-4 semanas',
    prerequisites: ['JS sólido', 'HTTP'],
    topics: ['Express', 'Rotas', 'Middlewares', 'JSON', 'Status codes'],
    why: 'Backend é onde você entende o stack completo.',
    build: 'API REST para o CRUD',
    ugProjects: [7, 8],
    commonMistakes: ['Sem validação de entrada', 'Erros genéricos'],
    tips: ['Valide input sempre', 'Documente endpoints'],
  },
  {
    num: 8,
    title: 'PostgreSQL e SQL',
    difficulty: 'Média',
    duration: '3 semanas',
    prerequisites: ['Lógica'],
    topics: ['SELECT', 'JOIN', 'Relacionamentos', 'Índices', 'RLS'],
    why: 'Bancos relacionais são o coração dos apps reais.',
    build: 'Esquema para o SaaS de notas',
    ugProjects: [7, 8],
    commonMistakes: ['N+1 queries', 'Sem índices'],
    tips: ['Use EXPLAIN', 'Modele antes de codar'],
  },
  {
    num: 9,
    title: 'DevOps: CI/CD e deploy',
    difficulty: 'Média',
    duration: '2-3 semanas',
    prerequisites: ['Git', 'Terminal'],
    topics: ['GitHub Actions', 'Vercel', 'Ambientes', 'Variáveis'],
    why: 'Deploy automatizado reduz medo e acelera entrega.',
    build: 'Pipeline de deploy automático',
    ugProjects: [9],
    commonMistakes: ['Secrets no repo', 'Sem testes no CI'],
    tips: ['Restrinja permissões', 'Faça testes rodarem no CI'],
  },
  {
    num: 10,
    title: 'Testes E2E e arquitetura',
    difficulty: 'Alta',
    duration: '4-6 semanas',
    prerequisites: ['TS', 'Node', 'React'],
    topics: ['Vitest', 'Playwright', 'Arquitetura', 'ADR'],
    why: 'Engenheiros de elite escrevem testes e justificam decisões.',
    build: 'LMS com cobertura de testes ≥ 80%',
    ugProjects: [9, 10],
    commonMistakes: ['Testar implementação em vez de comportamento'],
    tips: ['Escreva testes que sobrevivem a refactor', 'Documente decisões'],
  },
]

export const TECH_PROJECT_MAP: { tech: string; projects: number[] }[] = [
  { tech: 'HTML/CSS', projects: [1, 2] },
  { tech: 'JavaScript', projects: [1, 2, 3] },
  { tech: 'React', projects: [3, 4, 5, 6] },
  { tech: 'Next.js', projects: [5, 6] },
  { tech: 'TypeScript', projects: [5, 6, 7, 8] },
  { tech: 'Node', projects: [7, 8] },
  { tech: 'PostgreSQL', projects: [7, 8] },
  { tech: 'DevOps', projects: [9] },
  { tech: 'Testes', projects: [9, 10] },
  { tech: 'Arquitetura', projects: [10] },
]